### ISSUE TITLE
cordova-plugin-websocket required

### ISSUE THREAD

**Issue by mpfurnari** [estbeetoo/cordova-plugin-mqtt-pahojs#1]
Thanks for the plugin! It took a bit to figure this out, but it seems you have to have cordova-plugin-websocket installed to successfully connect to wss using this plugin. Maybe a comment in your readme or a dependency in your code?

**Comment by aborovsky** [comment]
@mpfurnari You are welcome =)

About `cordova-plugin-websocket`.
According to [library's page](https://www.npmjs.com/package/cordova-plugin-websocket) desciption:

- This is a Cordova plugin ... makes WebSocket (RFC6455) available on Android
- Since  Android 4.4.x (KitKat) and later support WebSocket, this plugin is NOT used on there by default.

Conclusions:

- iOs build do not need `cordova-plugin-websocket` at all
- fresh versions of Android support websockets without `cordova-plugin-websocket`

WSS works too with native websockets implementation for each platform (iOs, Android).

Let me ask: do you support old Android versions? Why do you need `cordova-plugin-websocket`?

**Comment by mpfurnari** [comment]
Thanks again... excellent followup! 

Without the websocket plugin, I was getting an error "ERR_NAME_NOT_RESOLVED". Once I added it, the error resolved.  My app is built to support minSdkVersion="16", so Android 4.1. I suppose I could up the min version, but I'm not certain of the minimum required by my customers.

So, maybe just a note someone in your readme might help the next person who comes across your plugin? (It took me a couple of days to figure it out... I'm kinda new to cordova...) 

I was able to get both Android and ios to work, so I'm really thankful for what you've done with the plugin!
